### ISSUE TITLE
Feature Request: Drift Correction

### ISSUE THREAD

**Issue by dgiebert** [kubewarden/fleet-example#4]
### Is your feature request related to a problem?

In Version 0.8 of Fleet Drift Detection and Correction was implemented [docs](https://fleet.rancher.io/ref-crds#correctdrift).

We could make this repo use the feature to enforce best practices (git as single source of truth)

### Solution you'd like

The needed flags would imo be
```yaml
  correctDrift:
    enabled: true
    force: true 
```
This will enforce the consistency by making sure all resources are present in the configured way.
